apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: uat-overlay

namespace: uat

resources:
- ../../base/environments/uat
- ../../base/apps/ingress

patchesStrategicMerge:
- uat.yaml