apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app2
  name: app2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2-containter
        image: tutum/hello-world
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app2
  name: app2-service
spec:
  type: NodePort
  ports:
  - name: webport
    port: 80
    targetPort: 80
  selector:
    app: app2    